/* Copyright 2023 Solidsoft Reply Ltd.

 *     Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at

 * http://www.apache.org/licenses/LICENSE-2.0

 * Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 * limitations under the License.
 * */

namespace Solidsoft.Reply.Iso3166;

public static class Country {
    public static IReadOnlyDictionary<string, ICountry> EnglishNames = new Dictionary<string, ICountry>()
    {
        { "Afghanistan", new Afghanistan() },
        { "Albania", new Albania() },
        { "Algeria", new Algeria() },
        { "American Samoa", new AmericanSamoa() },
        { "Andorra", new Andorra() },
        { "Angola", new Angola() },
        { "Anguilla", new Anguilla() },
        { "Antarctica", new Antarctica() },
        { "Antigua and Barbuda", new AntiguaAndBarbuda() },
        { "Argentina", new Argentina() },
        { "Armenia", new Armenia() },
        { "Aruba", new Aruba() },
        { "Australia", new Australia() },
        { "Austria", new Austria() },
        { "Azerbaijan", new Azerbaijan() },
        { "Bahamas (the)", new Bahamas() },
        { "Bahrain", new Bahrain() },
        { "Bangladesh", new Bangladesh() },
        { "Barbados", new Barbados() },
        { "Belarus", new Belarus() },
        { "Belgium", new Belgium() },
        { "Belize", new Belize() },
        { "Benin", new Benin() },
        { "Bermuda", new Bermuda() },
        { "Åland Islands", new ÅlandIslands() },
        { "Bhutan", new Bhutan() },
        { "Bolivia (Plurinational State of)", new Bolivia() },
        { "Bonaire, Sint Eustatius and Saba", new BonaireSintEustatiusAndSaba() },
        { "Bosnia and Herzegovina", new BosniaAndHerzegovina() },
        { "Botswana", new Botswana() },
        { "Bouvet Island", new BouvetIsland() },
        { "Brazil", new Brazil() },
        { "British Indian Ocean Territory (the)", new BritishIndianOceanTerritory() },
        { "Brunei Darussalam", new BruneiDarussalam() },
        { "Bulgaria", new Bulgaria() },
        { "Burkina Faso", new BurkinaFaso() },
        { "Burundi", new Burundi() },
        { "Cabo Verde", new CaboVerde() },
        { "Cambodia", new Cambodia() },
        { "Cameroon", new Cameroon() },
        { "Canada", new Canada() },
        { "Cayman Islands (the)", new CaymanIslands() },
        { "Central African Republic (the)", new CentralAfricanRepublic() },
        { "Chad", new Chad() },
        { "Chile", new Chile() },
        { "China", new China() },
        { "Christmas Island", new ChristmasIsland() },
        { "Cocos (Keeling) Islands (the)", new CocosIslands() },
        { "Colombia", new Colombia() },
        { "Comoros (the)", new Comoros() },
        { "Congo (the Democratic Republic of the)", new DemocraticRepublicOfTheCongo() },
        { "Congo (the)", new Congo() },
        { "Cook Islands (the)", new CookIslands() },
        { "Costa Rica", new CostaRica() },
        { "Croatia", new Croatia() },
        { "Cuba", new Cuba() },
        { "Curaçao", new Curaçao() },
        { "Cyprus", new Cyprus() },
        { "Czechia", new Czechia() },
        { "Côte d'Ivoire", new CôteDivoire() },
        { "Denmark", new Denmark() },
        { "Djibouti", new Djibouti() },
        { "Dominica", new Dominica() },
        { "Dominican Republic (the)", new DominicanRepublic() },
        { "Ecuador", new Ecuador() },
        { "Egypt", new Egypt() },
        { "El Salvador", new ElSalvador() },
        { "Equatorial Guinea", new EquatorialGuinea() },
        { "Eritrea", new Eritrea() },
        { "Estonia", new Estonia() },
        { "Eswatini", new Eswatini() },
        { "Ethiopia", new Ethiopia() },
        { "Falkland Islands (the) [Malvinas]", new FalklandIslands() },
        { "Faroe Islands (the)", new FaroeIslands() },
        { "Fiji", new Fiji() },
        { "Finland", new Finland() },
        { "France", new France() },
        { "French Guiana", new FrenchGuiana() },
        { "French Polynesia", new FrenchPolynesia() },
        { "French Southern Territories (the)", new FrenchSouthernTerritories() },
        { "Gabon", new Gabon() },
        { "Gambia (the)", new Gambia() },
        { "Georgia", new Georgia() },
        { "Germany", new Germany() },
        { "Ghana", new Ghana() },
        { "Gibraltar", new Gibraltar() },
        { "Greece", new Greece() },
        { "Greenland", new Greenland() },
        { "Grenada", new Grenada() },
        { "Guadeloupe", new Guadeloupe() },
        { "Guam", new Guam() },
        { "Guatemala", new Guatemala() },
        { "Guernsey", new Guernsey() },
        { "Guinea", new Guinea() },
        { "Guinea-Bissau", new GuineaBissau() },
        { "Guyana", new Guyana() },
        { "Haiti", new Haiti() },
        { "Heard Island and McDonald Islands", new HeardIslandAndMcDonaldIslands() },
        { "Holy See (the)", new HolySee() },
        { "Honduras", new Honduras() },
        { "Hong Kong", new HongKong() },
        { "Hungary", new Hungary() },
        { "Iceland", new Iceland() },
        { "India", new India() },
        { "Indonesia", new Indonesia() },
        { "Iran (Islamic Republic of)", new Iran() },
        { "Iraq", new Iraq() },
        { "Ireland", new Ireland() },
        { "Isle of Man", new IsleOfMan() },
        { "Israel", new Israel() },
        { "Italy", new Italy() },
        { "Jamaica", new Jamaica() },
        { "Japan", new Japan() },
        { "Jersey", new Jersey() },
        { "Jordan", new Jordan() },
        { "Kazakhstan", new Kazakhstan() },
        { "Kenya", new Kenya() },
        { "Kiribati", new Kiribati() },
        { "Korea (the Democratic People's Republic of)", new NorthKorea() },
        { "Korea (the Republic of)", new SouthKorea() },
        { "Kuwait", new Kuwait() },
        { "Kyrgyzstan", new Kyrgyzstan() },
        { "Lao People's Democratic Republic (the)", new LaoPeoplesDemocraticRepublic() },
        { "Latvia", new Latvia() },
        { "Lebanon", new Lebanon() },
        { "Lesotho", new Lesotho() },
        { "Liberia", new Liberia() },
        { "Libya", new Libya() },
        { "Liechtenstein", new Liechtenstein() },
        { "Lithuania", new Lithuania() },
        { "Luxembourg", new Luxembourg() },
        { "Macao", new Macao() },
        { "Madagascar", new Madagascar() },
        { "Malawi", new Malawi() },
        { "Malaysia", new Malaysia() },
        { "Maldives", new Maldives() },
        { "Mali", new Mali() },
        { "Malta", new Malta() },
        { "Marshall Islands (the)", new MarshallIslands() },
        { "Martinique", new Martinique() },
        { "Mauritania", new Mauritania() },
        { "Mauritius", new Mauritius() },
        { "Mayotte", new Mayotte() },
        { "Mexico", new Mexico() },
        { "Micronesia (Federated States of)", new Micronesia() },
        { "Moldova (the Republic of)", new Moldova() },
        { "Monaco", new Monaco() },
        { "Mongolia", new Mongolia() },
        { "Montenegro", new Montenegro() },
        { "Montserrat", new Montserrat() },
        { "Morocco", new Morocco() },
        { "Mozambique", new Mozambique() },
        { "Myanmar", new Myanmar() },
        { "Namibia", new Namibia() },
        { "Nauru", new Nauru() },
        { "Nepal", new Nepal() },
        { "Netherlands (the)", new Netherlands() },
        { "New Caledonia", new NewCaledonia() },
        { "New Zealand", new NewZealand() },
        { "Nicaragua", new Nicaragua() },
        { "Niger (the)", new Niger() },
        { "Nigeria", new Nigeria() },
        { "Niue", new Niue() },
        { "Norfolk Island", new NorfolkIsland() },
        { "North Macedonia", new NorthMacedonia() },
        { "Northern Mariana Islands (the)", new NorthernMarianaIslands() },
        { "Norway", new Norway() },
        { "Oman", new Oman() },
        { "Pakistan", new Pakistan() },
        { "Palau", new Palau() },
        { "Palestine, State of", new StateOfPalestine() },
        { "Panama", new Panama() },
        { "Papua New Guinea", new PapuaNewGuinea() },
        { "Paraguay", new Paraguay() },
        { "Peru", new Peru() },
        { "Philippines (the)", new Philippines() },
        { "Pitcairn", new Pitcairn() },
        { "Poland", new Poland() },
        { "Portugal", new Portugal() },
        { "Puerto Rico", new PuertoRico() },
        { "Qatar", new Qatar() },
        { "Romania", new Romania() },
        { "Russian Federation (the)", new RussianFederation() },
        { "Rwanda", new Rwanda() },
        { "Réunion", new Réunion() },
        { "Saint Barthélemy", new SaintBarthélemy() },
        { "Saint Helena, Ascension and Tristan da Cunha", new SaintHelenaAscensionAndTristanDaCunha() },
        { "Saint Kitts and Nevis", new SaintKittsAndNevis() },
        { "Saint Lucia", new SaintLucia() },
        { "Saint Martin (French part)", new SaintMartin() },
        { "Saint Pierre and Miquelon", new SaintPierreAndMiquelon() },
        { "Saint Vincent and the Grenadines", new SaintVincentAndTheGrenadines() },
        { "Samoa", new Samoa() },
        { "San Marino", new SanMarino() },
        { "Sao Tome and Principe", new SaoTomeAndPrincipe() },
        { "Saudi Arabia", new SaudiArabia() },
        { "Senegal", new Senegal() },
        { "Serbia", new Serbia() },
        { "Seychelles", new Seychelles() },
        { "Sierra Leone", new SierraLeone() },
        { "Singapore", new Singapore() },
        { "Sint Maarten (Dutch part)", new SintMaarten() },
        { "Slovakia", new Slovakia() },
        { "Slovenia", new Slovenia() },
        { "Solomon Islands", new SolomonIslands() },
        { "Somalia", new Somalia() },
        { "South Africa", new SouthAfrica() },
        { "South Georgia and the South Sandwich Islands", new SouthGeorgiaAndTheSouthSandwichIslands() },
        { "South Sudan", new SouthSudan() },
        { "Spain", new Spain() },
        { "Sri Lanka", new SriLanka() },
        { "Sudan (the)", new Sudan() },
        { "Suriname", new Suriname() },
        { "Svalbard and Jan Mayen", new SvalbardAndJanMayen() },
        { "Sweden", new Sweden() },
        { "Switzerland", new Switzerland() },
        { "Syrian Arab Republic (the)", new SyrianArabRepublic() },
        { "Taiwan (Province of China)", new Taiwan() },
        { "Tajikistan", new Tajikistan() },
        { "Tanzania, the United Republic of", new TheUnitedRepublicOfTanzania() },
        { "Thailand", new Thailand() },
        { "Timor-Leste", new TimorLeste() },
        { "Togo", new Togo() },
        { "Tokelau", new Tokelau() },
        { "Tonga", new Tonga() },
        { "Trinidad and Tobago", new TrinidadAndTobago() },
        { "Tunisia", new Tunisia() },
        { "Turkmenistan", new Turkmenistan() },
        { "Turks and Caicos Islands (the)", new TurksAndCaicosIslands() },
        { "Tuvalu", new Tuvalu() },
        { "Türkiye", new Türkiye() },
        { "Uganda", new Uganda() },
        { "Ukraine", new Ukraine() },
        { "United Arab Emirates (the)", new UnitedArabEmirates() },
        { "United Kingdom of Great Britain and Northern Ireland (the)", new UnitedKingdomOfGreatBritainAndNorthernIreland() },
        { "United States Minor Outlying Islands (the)", new UnitedStatesMinorOutlyingIslands() },
        { "United States of America (the)", new UnitedStatesOfAmerica() },
        { "Uruguay", new Uruguay() },
        { "Uzbekistan", new Uzbekistan() },
        { "Vanuatu", new Vanuatu() },
        { "Venezuela (Bolivarian Republic of)", new Venezuela() },
        { "Viet Nam", new VietNam() },
        { "Virgin Islands (British)", new BritishVirginIslands() },
        { "Virgin Islands (U.S.)", new UsVirginIslands() },
        { "Wallis and Futuna", new WallisAndFutuna() },
        { "Western Sahara", new WesternSahara() },
        { "Yemen", new Yemen() },
        { "Zambia", new Zambia() },
        { "Zimbabwe", new Zimbabwe() }
    };

    public static IReadOnlyDictionary<string, ICountry> FrenchNames = new Dictionary<string, ICountry>() {
        { "Afghanistan (l')", new Afghanistan() },
        { "Albanie (l')", new Albania() },
        { "Algérie (l')", new Algeria() },
        { "Samoa américaines (les)", new AmericanSamoa() },
        { "Andorre (l')", new Andorra() },
        { "Angola (l')", new Angola() },
        { "Anguilla", new Anguilla() },
        { "Antarctique (l')", new Antarctica() },
        { "Antigua-et-Barbuda", new AntiguaAndBarbuda() },
        { "Argentine (l')", new Argentina() },
        { "Arménie (l')", new Armenia() },
        { "Aruba", new Aruba() },
        { "Australie (l')", new Australia() },
        { "Autriche (l')", new Austria() },
        { "Azerbaïdjan (l')", new Azerbaijan() },
        { "Bahamas (les)", new Bahamas() },
        { "Bahreïn", new Bahrain() },
        { "Bangladesh (le)", new Bangladesh() },
        { "Barbade (la)", new Barbados() },
        { "Bélarus (le)", new Belarus() },
        { "Belgique (la)", new Belgium() },
        { "Belize (le)", new Belize() },
        { "Bénin (le)", new Benin() },
        { "Bermudes (les)", new Bermuda() },
        { "Åland (les Îles)", new ÅlandIslands() },
        { "Bhoutan (le)", new Bhutan() },
        { "Bolivie (État plurinational de)", new Bolivia() },
        { "Bonaire, Saint-Eustache et Saba", new BonaireSintEustatiusAndSaba() },
        { "Bosnie-Herzégovine (la)", new BosniaAndHerzegovina() },
        { "Botswana (le)", new Botswana() },
        { "Bouvet (l'Île)", new BouvetIsland() },
        { "Brésil (le)", new Brazil() },
        { "Indien (le Territoire britannique de l'océan)", new BritishIndianOceanTerritory() },
        { "Brunéi Darussalam (le)", new BruneiDarussalam() },
        { "Bulgarie (la)", new Bulgaria() },
        { "Burkina Faso (le)", new BurkinaFaso() },
        { "Burundi (le)", new Burundi() },
        { "Cabo Verde", new CaboVerde() },
        { "Cambodge (le)", new Cambodia() },
        { "Cameroun (le)", new Cameroon() },
        { "Canada (le)", new Canada() },
        { "Caïmans (les Îles)", new CaymanIslands() },
        { "République centrafricaine (la)", new CentralAfricanRepublic() },
        { "Tchad (le)", new Chad() },
        { "Chili (le)", new Chile() },
        { "Chine (la)", new China() },
        { "Christmas (l'Île)", new ChristmasIsland() },
        { "Cocos (les Îles)/ Keeling (les Îles)", new CocosIslands() },
        { "Colombie (la)", new Colombia() },
        { "Comores (les)", new Comoros() },
        { "Congo (la République démocratique du)", new DemocraticRepublicOfTheCongo() },
        { "Congo (le)", new Congo() },
        { "Cook (les Îles)", new CookIslands() },
        { "Costa Rica (le)", new CostaRica() },
        { "Croatie (la)", new Croatia() },
        { "Cuba", new Cuba() },
        { "Curaçao", new Curaçao() },
        { "Chypre", new Cyprus() },
        { "Tchéquie (la)", new Czechia() },
        { "Côte d'Ivoire (la)", new CôteDivoire() },
        { "Danemark (le)", new Denmark() },
        { "Djibouti", new Djibouti() },
        { "Dominique (la)", new Dominica() },
        { "dominicaine (la République)", new DominicanRepublic() },
        { "Équateur (l')", new Ecuador() },
        { "Égypte (l')", new Egypt() },
        { "El Salvador", new ElSalvador() },
        { "Guinée équatoriale (la)", new EquatorialGuinea() },
        { "Érythrée (l')", new Eritrea() },
        { "Estonie (l')", new Estonia() },
        { "Eswatini (l')", new Eswatini() },
        { "Éthiopie (l')", new Ethiopia() },
        { "Falkland (les Îles)/Malouines (les Îles)", new FalklandIslands() },
        { "Féroé (les Îles)", new FaroeIslands() },
        { "Fidji (les)", new Fiji() },
        { "Finlande (la)", new Finland() },
        { "France (la)", new France() },
        { "Guyane française (la)", new FrenchGuiana() },
        { "Polynésie française (la)", new FrenchPolynesia() },
        { "Terres australes françaises (les)", new FrenchSouthernTerritories() },
        { "Gabon (le)", new Gabon() },
        { "Gambie (la)", new Gambia() },
        { "Géorgie (la)", new Georgia() },
        { "Allemagne (l')", new Germany() },
        { "Ghana (le)", new Ghana() },
        { "Gibraltar", new Gibraltar() },
        { "Grèce (la)", new Greece() },
        { "Groenland (le)", new Greenland() },
        { "Grenade (la)", new Grenada() },
        { "Guadeloupe (la)", new Guadeloupe() },
        { "Guam", new Guam() },
        { "Guatemala (le)", new Guatemala() },
        { "Guernesey", new Guernsey() },
        { "Guinée (la)", new Guinea() },
        { "Guinée-Bissau (la)", new GuineaBissau() },
        { "Guyana (le)", new Guyana() },
        { "Haïti", new Haiti() },
        { "Heard-et-Îles MacDonald (l'Île)", new HeardIslandAndMcDonaldIslands() },
        { "Saint-Siège (le)", new HolySee() },
        { "Honduras (le)", new Honduras() },
        { "Hong Kong", new HongKong() },
        { "Hongrie (la)", new Hungary() },
        { "Islande (l')", new Iceland() },
        { "Inde (l')", new India() },
        { "Indonésie (l')", new Indonesia() },
        { "Iran (République Islamique d')", new Iran() },
        { "Iraq (l')", new Iraq() },
        { "Irlande (l')", new Ireland() },
        { "Île de Man", new IsleOfMan() },
        { "Israël", new Israel() },
        { "Italie (l')", new Italy() },
        { "Jamaïque (la)", new Jamaica() },
        { "Japon (le)", new Japan() },
        { "Jersey", new Jersey() },
        { "Jordanie (la)", new Jordan() },
        { "Kazakhstan (le)", new Kazakhstan() },
        { "Kenya (le)", new Kenya() },
        { "Kiribati", new Kiribati() },
        { "Corée (la République populaire démocratique de)", new NorthKorea() },
        { "Corée (la République de)", new SouthKorea() },
        { "Koweït (le)", new Kuwait() },
        { "Kirghizistan (le)", new Kyrgyzstan() },
        { "Lao (la République démocratique populaire)", new LaoPeoplesDemocraticRepublic() },
        { "Lettonie (la)", new Latvia() },
        { "Liban (le)", new Lebanon() },
        { "Lesotho (le)", new Lesotho() },
        { "Libéria (le)", new Liberia() },
        { "Libye (la)", new Libya() },
        { "Liechtenstein (le)", new Liechtenstein() },
        { "Lituanie (la)", new Lithuania() },
        { "Luxembourg (le)", new Luxembourg() },
        { "Macao", new Macao() },
        { "Madagascar", new Madagascar() },
        { "Malawi (le)", new Malawi() },
        { "Malaisie (la)", new Malaysia() },
        { "Maldives (les)", new Maldives() },
        { "Mali (le)", new Mali() },
        { "Malte", new Malta() },
        { "Marshall (les Îles)", new MarshallIslands() },
        { "Martinique (la)", new Martinique() },
        { "Mauritanie (la)", new Mauritania() },
        { "Maurice", new Mauritius() },
        { "Mayotte", new Mayotte() },
        { "Mexique (le)", new Mexico() },
        { "Micronésie (États fédérés de)", new Micronesia() },
        { "Moldova (la République de)", new Moldova() },
        { "Monaco", new Monaco() },
        { "Mongolie (la)", new Mongolia() },
        { "Monténégro (le)", new Montenegro() },
        { "Montserrat", new Montserrat() },
        { "Maroc (le)", new Morocco() },
        { "Mozambique (le)", new Mozambique() },
        { "Myanmar (le)", new Myanmar() },
        { "Namibie (la)", new Namibia() },
        { "Nauru", new Nauru() },
        { "Népal (le)", new Nepal() },
        { "Pays-Bas (les)", new Netherlands() },
        { "Nouvelle-Calédonie (la)", new NewCaledonia() },
        { "Nouvelle-Zélande (la)", new NewZealand() },
        { "Nicaragua (le)", new Nicaragua() },
        { "Niger (le)", new Niger() },
        { "Nigéria (le)", new Nigeria() },
        { "Niue", new Niue() },
        { "Norfolk (l'Île)", new NorfolkIsland() },
        { "Macédoine du Nord (la)", new NorthMacedonia() },
        { "Mariannes du Nord (les Îles)", new NorthernMarianaIslands() },
        { "Norvège (la)", new Norway() },
        { "Oman", new Oman() },
        { "Pakistan (le)", new Pakistan() },
        { "Palaos (les)", new Palau() },
        { "Palestine, État de", new StateOfPalestine() },
        { "Panama (le)", new Panama() },
        { "Papouasie-Nouvelle-Guinée (la)", new PapuaNewGuinea() },
        { "Paraguay (le)", new Paraguay() },
        { "Pérou (le)", new Peru() },
        { "Philippines (les)", new Philippines() },
        { "Pitcairn", new Pitcairn() },
        { "Pologne (la)", new Poland() },
        { "Portugal (le)", new Portugal() },
        { "Porto Rico", new PuertoRico() },
        { "Qatar (le)", new Qatar() },
        { "Roumanie (la)", new Romania() },
        { "Russie (la Fédération de)", new RussianFederation() },
        { "Rwanda (le)", new Rwanda() },
        { "Réunion (La)", new Réunion() },
        { "Saint-Barthélemy", new SaintBarthélemy() },
        { "Sainte-Hélène, Ascension et Tristan da Cunha", new SaintHelenaAscensionAndTristanDaCunha() },
        { "Saint-Kitts-et-Nevis", new SaintKittsAndNevis() },
        { "Sainte-Lucie", new SaintLucia() },
        { "Saint-Martin (partie française)", new SaintMartin() },
        { "Saint-Pierre-et-Miquelon", new SaintPierreAndMiquelon() },
        { "Saint-Vincent-et-les Grenadines", new SaintVincentAndTheGrenadines() },
        { "Samoa (le)", new Samoa() },
        { "Saint-Marin", new SanMarino() },
        { "Sao Tomé-et-Principe", new SaoTomeAndPrincipe() },
        { "Arabie saoudite (l')", new SaudiArabia() },
        { "Sénégal (le)", new Senegal() },
        { "Serbie (la)", new Serbia() },
        { "Seychelles (les)", new Seychelles() },
        { "Sierra Leone (la)", new SierraLeone() },
        { "Singapour", new Singapore() },
        { "Saint-Martin (partie néerlandaise)", new SintMaarten() },
        { "Slovaquie (la)", new Slovakia() },
        { "Slovénie (la)", new Slovenia() },
        { "Salomon (les Îles)", new SolomonIslands() },
        { "Somalie (la)", new Somalia() },
        { "Afrique du Sud (l')", new SouthAfrica() },
        { "Géorgie du Sud-et-les Îles Sandwich du Sud (la)", new SouthGeorgiaAndTheSouthSandwichIslands() },
        { "Soudan du Sud (le)", new SouthSudan() },
        { "Espagne (l')", new Spain() },
        { "Sri Lanka", new SriLanka() },
        { "Soudan (le)", new Sudan() },
        { "Suriname (le)", new Suriname() },
        { "Svalbard et l'Île Jan Mayen (le)", new SvalbardAndJanMayen() },
        { "Suède (la)", new Sweden() },
        { "Suisse (la)", new Switzerland() },
        { "République arabe syrienne (la)", new SyrianArabRepublic() },
        { "Taïwan (Province de Chine)", new Taiwan() },
        { "Tadjikistan (le)", new Tajikistan() },
        { "Tanzanie (la République-Unie de)", new TheUnitedRepublicOfTanzania() },
        { "Thaïlande (la)", new Thailand() },
        { "Timor-Leste (le)", new TimorLeste() },
        { "Togo (le)", new Togo() },
        { "Tokelau (les)", new Tokelau() },
        { "Tonga (les)", new Tonga() },
        { "Trinité-et-Tobago (la)", new TrinidadAndTobago() },
        { "Tunisie (la)", new Tunisia() },
        { "Turkménistan (le)", new Turkmenistan() },
        { "Turks-et-Caïcos (les Îles)", new TurksAndCaicosIslands() },
        { "Tuvalu (les)", new Tuvalu() },
        { "Türkiye (la)", new Türkiye() },
        { "Ouganda (l')", new Uganda() },
        { "Ukraine (l')", new Ukraine() },
        { "Émirats arabes unis (les)", new UnitedArabEmirates() },
        { "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord (le)", new UnitedKingdomOfGreatBritainAndNorthernIreland() },
        { "Îles mineures éloignées des États-Unis (les)", new UnitedStatesMinorOutlyingIslands() },
        { "États-Unis d'Amérique (les)", new UnitedStatesOfAmerica() },
        { "Uruguay (l')", new Uruguay() },
        { "Ouzbékistan (l')", new Uzbekistan() },
        { "Vanuatu (le)", new Vanuatu() },
        { "Venezuela (République bolivarienne du)", new Venezuela() },
        { "Viet Nam (le)", new VietNam() },
        { "Vierges britanniques (les Îles)", new BritishVirginIslands() },
        { "Vierges des États-Unis (les Îles)", new UsVirginIslands() },
        { "Wallis-et-Futuna", new WallisAndFutuna() },
        { "Sahara occidental (le)", new WesternSahara() },
        { "Yémen (le)", new Yemen() },
        { "Zambie (la)", new Zambia() },
        { "Zimbabwe (le)", new Zimbabwe() }
    };

    public static IReadOnlyDictionary<string, ICountry> Alpha2Codes = new Dictionary<string, ICountry>()
    {
        { "AF", new Afghanistan() },
        { "AL", new Albania() },
        { "DZ", new Algeria() },
        { "AS", new AmericanSamoa() },
        { "AD", new Andorra() },
        { "AO", new Angola() },
        { "AI", new Anguilla() },
        { "AQ", new Antarctica() },
        { "AG", new AntiguaAndBarbuda() },
        { "AR", new Argentina() },
        { "AM", new Armenia() },
        { "AW", new Aruba() },
        { "AU", new Australia() },
        { "AT", new Austria() },
        { "AZ", new Azerbaijan() },
        { "BS", new Bahamas() },
        { "BH", new Bahrain() },
        { "BD", new Bangladesh() },
        { "BB", new Barbados() },
        { "BY", new Belarus() },
        { "BE", new Belgium() },
        { "BZ", new Belize() },
        { "BJ", new Benin() },
        { "BM", new Bermuda() },
        { "AX", new ÅlandIslands() },
        { "BT", new Bhutan() },
        { "BO", new Bolivia() },
        { "BQ", new BonaireSintEustatiusAndSaba() },
        { "BA", new BosniaAndHerzegovina() },
        { "BW", new Botswana() },
        { "BV", new BouvetIsland() },
        { "BR", new Brazil() },
        { "IO", new BritishIndianOceanTerritory() },
        { "BN", new BruneiDarussalam() },
        { "BG", new Bulgaria() },
        { "BF", new BurkinaFaso() },
        { "BI", new Burundi() },
        { "CV", new CaboVerde() },
        { "KH", new Cambodia() },
        { "CM", new Cameroon() },
        { "CA", new Canada() },
        { "KY", new CaymanIslands() },
        { "CF", new CentralAfricanRepublic() },
        { "TD", new Chad() },
        { "CL", new Chile() },
        { "CN", new China() },
        { "CX", new ChristmasIsland() },
        { "CC", new CocosIslands() },
        { "CO", new Colombia() },
        { "KM", new Comoros() },
        { "CD", new DemocraticRepublicOfTheCongo() },
        { "CG", new Congo() },
        { "CK", new CookIslands() },
        { "CR", new CostaRica() },
        { "HR", new Croatia() },
        { "CU", new Cuba() },
        { "CW", new Curaçao() },
        { "CY", new Cyprus() },
        { "CZ", new Czechia() },
        { "CI", new CôteDivoire() },
        { "DK", new Denmark() },
        { "DJ", new Djibouti() },
        { "DM", new Dominica() },
        { "DO", new DominicanRepublic() },
        { "EC", new Ecuador() },
        { "EG", new Egypt() },
        { "SV", new ElSalvador() },
        { "GQ", new EquatorialGuinea() },
        { "ER", new Eritrea() },
        { "EE", new Estonia() },
        { "SZ", new Eswatini() },
        { "ET", new Ethiopia() },
        { "FK", new FalklandIslands() },
        { "FO", new FaroeIslands() },
        { "FJ", new Fiji() },
        { "FI", new Finland() },
        { "FR", new France() },
        { "GF", new FrenchGuiana() },
        { "PF", new FrenchPolynesia() },
        { "TF", new FrenchSouthernTerritories() },
        { "GA", new Gabon() },
        { "GM", new Gambia() },
        { "GE", new Georgia() },
        { "DE", new Germany() },
        { "GH", new Ghana() },
        { "GI", new Gibraltar() },
        { "GR", new Greece() },
        { "GL", new Greenland() },
        { "GD", new Grenada() },
        { "GP", new Guadeloupe() },
        { "GU", new Guam() },
        { "GT", new Guatemala() },
        { "GG", new Guernsey() },
        { "GN", new Guinea() },
        { "GW", new GuineaBissau() },
        { "GY", new Guyana() },
        { "HT", new Haiti() },
        { "HM", new HeardIslandAndMcDonaldIslands() },
        { "VA", new HolySee() },
        { "HN", new Honduras() },
        { "HK", new HongKong() },
        { "HU", new Hungary() },
        { "IS", new Iceland() },
        { "IN", new India() },
        { "ID", new Indonesia() },
        { "IR", new Iran() },
        { "IQ", new Iraq() },
        { "IE", new Ireland() },
        { "IM", new IsleOfMan() },
        { "IL", new Israel() },
        { "IT", new Italy() },
        { "JM", new Jamaica() },
        { "JP", new Japan() },
        { "JE", new Jersey() },
        { "JO", new Jordan() },
        { "KZ", new Kazakhstan() },
        { "KE", new Kenya() },
        { "KI", new Kiribati() },
        { "KP", new NorthKorea() },
        { "KR", new SouthKorea() },
        { "KW", new Kuwait() },
        { "KG", new Kyrgyzstan() },
        { "LA", new LaoPeoplesDemocraticRepublic() },
        { "LV", new Latvia() },
        { "LB", new Lebanon() },
        { "LS", new Lesotho() },
        { "LR", new Liberia() },
        { "LY", new Libya() },
        { "LI", new Liechtenstein() },
        { "LT", new Lithuania() },
        { "LU", new Luxembourg() },
        { "MO", new Macao() },
        { "MG", new Madagascar() },
        { "MW", new Malawi() },
        { "MY", new Malaysia() },
        { "MV", new Maldives() },
        { "ML", new Mali() },
        { "MT", new Malta() },
        { "MH", new MarshallIslands() },
        { "MQ", new Martinique() },
        { "MR", new Mauritania() },
        { "MU", new Mauritius() },
        { "YT", new Mayotte() },
        { "MX", new Mexico() },
        { "FM", new Micronesia() },
        { "MD", new Moldova() },
        { "MC", new Monaco() },
        { "MN", new Mongolia() },
        { "ME", new Montenegro() },
        { "MS", new Montserrat() },
        { "MA", new Morocco() },
        { "MZ", new Mozambique() },
        { "MM", new Myanmar() },
        { "NA", new Namibia() },
        { "NR", new Nauru() },
        { "NP", new Nepal() },
        { "NL", new Netherlands() },
        { "NC", new NewCaledonia() },
        { "NZ", new NewZealand() },
        { "NI", new Nicaragua() },
        { "NE", new Niger() },
        { "NG", new Nigeria() },
        { "NU", new Niue() },
        { "NF", new NorfolkIsland() },
        { "MK", new NorthMacedonia() },
        { "MP", new NorthernMarianaIslands() },
        { "NO", new Norway() },
        { "OM", new Oman() },
        { "PK", new Pakistan() },
        { "PW", new Palau() },
        { "PS", new StateOfPalestine() },
        { "PA", new Panama() },
        { "PG", new PapuaNewGuinea() },
        { "PY", new Paraguay() },
        { "PE", new Peru() },
        { "PH", new Philippines() },
        { "PN", new Pitcairn() },
        { "PL", new Poland() },
        { "PT", new Portugal() },
        { "PR", new PuertoRico() },
        { "QA", new Qatar() },
        { "RO", new Romania() },
        { "RU", new RussianFederation() },
        { "RW", new Rwanda() },
        { "RE", new Réunion() },
        { "BL", new SaintBarthélemy() },
        { "SH", new SaintHelenaAscensionAndTristanDaCunha() },
        { "KN", new SaintKittsAndNevis() },
        { "LC", new SaintLucia() },
        { "MF", new SaintMartin() },
        { "PM", new SaintPierreAndMiquelon() },
        { "VC", new SaintVincentAndTheGrenadines() },
        { "WS", new Samoa() },
        { "SM", new SanMarino() },
        { "ST", new SaoTomeAndPrincipe() },
        { "SA", new SaudiArabia() },
        { "SN", new Senegal() },
        { "RS", new Serbia() },
        { "SC", new Seychelles() },
        { "SL", new SierraLeone() },
        { "SG", new Singapore() },
        { "SX", new SintMaarten() },
        { "SK", new Slovakia() },
        { "SI", new Slovenia() },
        { "SB", new SolomonIslands() },
        { "SO", new Somalia() },
        { "ZA", new SouthAfrica() },
        { "GS", new SouthGeorgiaAndTheSouthSandwichIslands() },
        { "SS", new SouthSudan() },
        { "ES", new Spain() },
        { "LK", new SriLanka() },
        { "SD", new Sudan() },
        { "SR", new Suriname() },
        { "SJ", new SvalbardAndJanMayen() },
        { "SE", new Sweden() },
        { "CH", new Switzerland() },
        { "SY", new SyrianArabRepublic() },
        { "TW", new Taiwan() },
        { "TJ", new Tajikistan() },
        { "TZ", new TheUnitedRepublicOfTanzania() },
        { "TH", new Thailand() },
        { "TL", new TimorLeste() },
        { "TG", new Togo() },
        { "TK", new Tokelau() },
        { "TO", new Tonga() },
        { "TT", new TrinidadAndTobago() },
        { "TN", new Tunisia() },
        { "TM", new Turkmenistan() },
        { "TC", new TurksAndCaicosIslands() },
        { "TV", new Tuvalu() },
        { "TR", new Türkiye() },
        { "UG", new Uganda() },
        { "UA", new Ukraine() },
        { "AE", new UnitedArabEmirates() },
        { "GB", new UnitedKingdomOfGreatBritainAndNorthernIreland() },
        { "UM", new UnitedStatesMinorOutlyingIslands() },
        { "US", new UnitedStatesOfAmerica() },
        { "UY", new Uruguay() },
        { "UZ", new Uzbekistan() },
        { "VU", new Vanuatu() },
        { "VE", new Venezuela() },
        { "VN", new VietNam() },
        { "VG", new BritishVirginIslands() },
        { "VI", new UsVirginIslands() },
        { "WF", new WallisAndFutuna() },
        { "EH", new WesternSahara() },
        { "YE", new Yemen() },
        { "ZM", new Zambia() },
        { "ZW", new Zimbabwe() }
    };

    public static IReadOnlyDictionary<string, ICountry> Alpha3Codes = new Dictionary<string, ICountry>
    {
        { "AFG", new Afghanistan() },
        { "ALB", new Albania() },
        { "DZA", new Algeria() },
        { "ASM", new AmericanSamoa() },
        { "AND", new Andorra() },
        { "AGO", new Angola() },
        { "AIA", new Anguilla() },
        { "ATA", new Antarctica() },
        { "ATG", new AntiguaAndBarbuda() },
        { "ARG", new Argentina() },
        { "ARM", new Armenia() },
        { "ABW", new Aruba() },
        { "AUS", new Australia() },
        { "AUT", new Austria() },
        { "AZE", new Azerbaijan() },
        { "BHS", new Bahamas() },
        { "BHR", new Bahrain() },
        { "BGD", new Bangladesh() },
        { "BRB", new Barbados() },
        { "BLR", new Belarus() },
        { "BEL", new Belgium() },
        { "BLZ", new Belize() },
        { "BEN", new Benin() },
        { "BMU", new Bermuda() },
        { "ALA", new ÅlandIslands() },
        { "BTN", new Bhutan() },
        { "BOL", new Bolivia() },
        { "BES", new BonaireSintEustatiusAndSaba() },
        { "BIH", new BosniaAndHerzegovina() },
        { "BWA", new Botswana() },
        { "BVT", new BouvetIsland() },
        { "BRA", new Brazil() },
        { "IOT", new BritishIndianOceanTerritory() },
        { "BRN", new BruneiDarussalam() },
        { "BGR", new Bulgaria() },
        { "BFA", new BurkinaFaso() },
        { "BDI", new Burundi() },
        { "CPV", new CaboVerde() },
        { "KHM", new Cambodia() },
        { "CMR", new Cameroon() },
        { "CAN", new Canada() },
        { "CYM", new CaymanIslands() },
        { "CAF", new CentralAfricanRepublic() },
        { "TCD", new Chad() },
        { "CHL", new Chile() },
        { "CHN", new China() },
        { "CXR", new ChristmasIsland() },
        { "CCK", new CocosIslands() },
        { "COL", new Colombia() },
        { "COM", new Comoros() },
        { "COD", new DemocraticRepublicOfTheCongo() },
        { "COG", new Congo() },
        { "COK", new CookIslands() },
        { "CRI", new CostaRica() },
        { "HRV", new Croatia() },
        { "CUB", new Cuba() },
        { "CUW", new Curaçao() },
        { "CYP", new Cyprus() },
        { "CZE", new Czechia() },
        { "CIV", new CôteDivoire() },
        { "DNK", new Denmark() },
        { "DJI", new Djibouti() },
        { "DMA", new Dominica() },
        { "DOM", new DominicanRepublic() },
        { "ECU", new Ecuador() },
        { "EGY", new Egypt() },
        { "SLV", new ElSalvador() },
        { "GNQ", new EquatorialGuinea() },
        { "ERI", new Eritrea() },
        { "EST", new Estonia() },
        { "SWZ", new Eswatini() },
        { "ETH", new Ethiopia() },
        { "FLK", new FalklandIslands() },
        { "FRO", new FaroeIslands() },
        { "FJI", new Fiji() },
        { "FIN", new Finland() },
        { "FRA", new France() },
        { "GUF", new FrenchGuiana() },
        { "PYF", new FrenchPolynesia() },
        { "ATF", new FrenchSouthernTerritories() },
        { "GAB", new Gabon() },
        { "GMB", new Gambia() },
        { "GEO", new Georgia() },
        { "DEU", new Germany() },
        { "GHA", new Ghana() },
        { "GIB", new Gibraltar() },
        { "GRC", new Greece() },
        { "GRL", new Greenland() },
        { "GRD", new Grenada() },
        { "GLP", new Guadeloupe() },
        { "GUM", new Guam() },
        { "GTM", new Guatemala() },
        { "GGY", new Guernsey() },
        { "GIN", new Guinea() },
        { "GNB", new GuineaBissau() },
        { "GUY", new Guyana() },
        { "HTI", new Haiti() },
        { "HMD", new HeardIslandAndMcDonaldIslands() },
        { "VAT", new HolySee() },
        { "HND", new Honduras() },
        { "HKG", new HongKong() },
        { "HUN", new Hungary() },
        { "ISL", new Iceland() },
        { "IND", new India() },
        { "IDN", new Indonesia() },
        { "IRN", new Iran() },
        { "IRQ", new Iraq() },
        { "IRL", new Ireland() },
        { "IMN", new IsleOfMan() },
        { "ISR", new Israel() },
        { "ITA", new Italy() },
        { "JAM", new Jamaica() },
        { "JPN", new Japan() },
        { "JEY", new Jersey() },
        { "JOR", new Jordan() },
        { "KAZ", new Kazakhstan() },
        { "KEN", new Kenya() },
        { "KIR", new Kiribati() },
        { "PRK", new NorthKorea() },
        { "KOR", new SouthKorea() },
        { "KWT", new Kuwait() },
        { "KGZ", new Kyrgyzstan() },
        { "LAO", new LaoPeoplesDemocraticRepublic() },
        { "LVA", new Latvia() },
        { "LBN", new Lebanon() },
        { "LSO", new Lesotho() },
        { "LBR", new Liberia() },
        { "LBY", new Libya() },
        { "LIE", new Liechtenstein() },
        { "LTU", new Lithuania() },
        { "LUX", new Luxembourg() },
        { "MAC", new Macao() },
        { "MDG", new Madagascar() },
        { "MWI", new Malawi() },
        { "MYS", new Malaysia() },
        { "MDV", new Maldives() },
        { "MLI", new Mali() },
        { "MLT", new Malta() },
        { "MHL", new MarshallIslands() },
        { "MTQ", new Martinique() },
        { "MRT", new Mauritania() },
        { "MUS", new Mauritius() },
        { "MYT", new Mayotte() },
        { "MEX", new Mexico() },
        { "FSM", new Micronesia() },
        { "MDA", new Moldova() },
        { "MCO", new Monaco() },
        { "MNG", new Mongolia() },
        { "MNE", new Montenegro() },
        { "MSR", new Montserrat() },
        { "MAR", new Morocco() },
        { "MOZ", new Mozambique() },
        { "MMR", new Myanmar() },
        { "NAM", new Namibia() },
        { "NRU", new Nauru() },
        { "NPL", new Nepal() },
        { "NLD", new Netherlands() },
        { "NCL", new NewCaledonia() },
        { "NZL", new NewZealand() },
        { "NIC", new Nicaragua() },
        { "NER", new Niger() },
        { "NGA", new Nigeria() },
        { "NIU", new Niue() },
        { "NFK", new NorfolkIsland() },
        { "MKD", new NorthMacedonia() },
        { "MNP", new NorthernMarianaIslands() },
        { "NOR", new Norway() },
        { "OMN", new Oman() },
        { "PAK", new Pakistan() },
        { "PLW", new Palau() },
        { "PSE", new StateOfPalestine() },
        { "PAN", new Panama() },
        { "PNG", new PapuaNewGuinea() },
        { "PRY", new Paraguay() },
        { "PER", new Peru() },
        { "PHL", new Philippines() },
        { "PCN", new Pitcairn() },
        { "POL", new Poland() },
        { "PRT", new Portugal() },
        { "PRI", new PuertoRico() },
        { "QAT", new Qatar() },
        { "ROU", new Romania() },
        { "RUS", new RussianFederation() },
        { "RWA", new Rwanda() },
        { "REU", new Réunion() },
        { "BLM", new SaintBarthélemy() },
        { "SHN", new SaintHelenaAscensionAndTristanDaCunha() },
        { "KNA", new SaintKittsAndNevis() },
        { "LCA", new SaintLucia() },
        { "MAF", new SaintMartin() },
        { "SPM", new SaintPierreAndMiquelon() },
        { "VCT", new SaintVincentAndTheGrenadines() },
        { "WSM", new Samoa() },
        { "SMR", new SanMarino() },
        { "STP", new SaoTomeAndPrincipe() },
        { "SAU", new SaudiArabia() },
        { "SEN", new Senegal() },
        { "SRB", new Serbia() },
        { "SYC", new Seychelles() },
        { "SLE", new SierraLeone() },
        { "SGP", new Singapore() },
        { "SXM", new SintMaarten() },
        { "SVK", new Slovakia() },
        { "SVN", new Slovenia() },
        { "SLB", new SolomonIslands() },
        { "SOM", new Somalia() },
        { "ZAF", new SouthAfrica() },
        { "SGS", new SouthGeorgiaAndTheSouthSandwichIslands() },
        { "SSD", new SouthSudan() },
        { "ESP", new Spain() },
        { "LKA", new SriLanka() },
        { "SDN", new Sudan() },
        { "SUR", new Suriname() },
        { "SJM", new SvalbardAndJanMayen() },
        { "SWE", new Sweden() },
        { "CHE", new Switzerland() },
        { "SYR", new SyrianArabRepublic() },
        { "TWN", new Taiwan() },
        { "TJK", new Tajikistan() },
        { "TZA", new TheUnitedRepublicOfTanzania() },
        { "THA", new Thailand() },
        { "TLS", new TimorLeste() },
        { "TGO", new Togo() },
        { "TKL", new Tokelau() },
        { "TON", new Tonga() },
        { "TTO", new TrinidadAndTobago() },
        { "TUN", new Tunisia() },
        { "TKM", new Turkmenistan() },
        { "TCA", new TurksAndCaicosIslands() },
        { "TUV", new Tuvalu() },
        { "TUR", new Türkiye() },
        { "UGA", new Uganda() },
        { "UKR", new Ukraine() },
        { "ARE", new UnitedArabEmirates() },
        { "GBR", new UnitedKingdomOfGreatBritainAndNorthernIreland() },
        { "UMI", new UnitedStatesMinorOutlyingIslands() },
        { "USA", new UnitedStatesOfAmerica() },
        { "URY", new Uruguay() },
        { "UZB", new Uzbekistan() },
        { "VUT", new Vanuatu() },
        { "VEN", new Venezuela() },
        { "VNM", new VietNam() },
        { "VGB", new BritishVirginIslands() },
        { "VIR", new UsVirginIslands() },
        { "WLF", new WallisAndFutuna() },
        { "ESH", new WesternSahara() },
        { "YEM", new Yemen() },
        { "ZMB", new Zambia() },
        { "ZWE", new Zimbabwe() }
    };

    public static IReadOnlyDictionary<string, ICountry> NumericCodes = new Dictionary<string, ICountry>()
    {
        { "004", new Afghanistan() },
        { "008", new Albania() },
        { "012", new Algeria() },
        { "016", new AmericanSamoa() },
        { "020", new Andorra() },
        { "024", new Angola() },
        { "660", new Anguilla() },
        { "010", new Antarctica() },
        { "028", new AntiguaAndBarbuda() },
        { "032", new Argentina() },
        { "051", new Armenia() },
        { "533", new Aruba() },
        { "036", new Australia() },
        { "040", new Austria() },
        { "031", new Azerbaijan() },
        { "044", new Bahamas() },
        { "048", new Bahrain() },
        { "050", new Bangladesh() },
        { "052", new Barbados() },
        { "112", new Belarus() },
        { "056", new Belgium() },
        { "084", new Belize() },
        { "204", new Benin() },
        { "060", new Bermuda() },
        { "248", new ÅlandIslands() },
        { "064", new Bhutan() },
        { "068", new Bolivia() },
        { "535", new BonaireSintEustatiusAndSaba() },
        { "070", new BosniaAndHerzegovina() },
        { "072", new Botswana() },
        { "074", new BouvetIsland() },
        { "076", new Brazil() },
        { "086", new BritishIndianOceanTerritory() },
        { "096", new BruneiDarussalam() },
        { "100", new Bulgaria() },
        { "854", new BurkinaFaso() },
        { "108", new Burundi() },
        { "132", new CaboVerde() },
        { "116", new Cambodia() },
        { "120", new Cameroon() },
        { "124", new Canada() },
        { "136", new CaymanIslands() },
        { "140", new CentralAfricanRepublic() },
        { "148", new Chad() },
        { "152", new Chile() },
        { "156", new China() },
        { "162", new ChristmasIsland() },
        { "166", new CocosIslands() },
        { "170", new Colombia() },
        { "174", new Comoros() },
        { "180", new DemocraticRepublicOfTheCongo() },
        { "178", new Congo() },
        { "184", new CookIslands() },
        { "188", new CostaRica() },
        { "191", new Croatia() },
        { "192", new Cuba() },
        { "531", new Curaçao() },
        { "196", new Cyprus() },
        { "203", new Czechia() },
        { "384", new CôteDivoire() },
        { "208", new Denmark() },
        { "262", new Djibouti() },
        { "212", new Dominica() },
        { "214", new DominicanRepublic() },
        { "218", new Ecuador() },
        { "818", new Egypt() },
        { "222", new ElSalvador() },
        { "226", new EquatorialGuinea() },
        { "232", new Eritrea() },
        { "233", new Estonia() },
        { "748", new Eswatini() },
        { "231", new Ethiopia() },
        { "238", new FalklandIslands() },
        { "234", new FaroeIslands() },
        { "242", new Fiji() },
        { "246", new Finland() },
        { "250", new France() },
        { "254", new FrenchGuiana() },
        { "258", new FrenchPolynesia() },
        { "260", new FrenchSouthernTerritories() },
        { "266", new Gabon() },
        { "270", new Gambia() },
        { "268", new Georgia() },
        { "276", new Germany() },
        { "288", new Ghana() },
        { "292", new Gibraltar() },
        { "300", new Greece() },
        { "304", new Greenland() },
        { "308", new Grenada() },
        { "312", new Guadeloupe() },
        { "316", new Guam() },
        { "320", new Guatemala() },
        { "831", new Guernsey() },
        { "324", new Guinea() },
        { "624", new GuineaBissau() },
        { "328", new Guyana() },
        { "332", new Haiti() },
        { "334", new HeardIslandAndMcDonaldIslands() },
        { "336", new HolySee() },
        { "340", new Honduras() },
        { "344", new HongKong() },
        { "348", new Hungary() },
        { "352", new Iceland() },
        { "356", new India() },
        { "360", new Indonesia() },
        { "364", new Iran() },
        { "368", new Iraq() },
        { "372", new Ireland() },
        { "833", new IsleOfMan() },
        { "376", new Israel() },
        { "380", new Italy() },
        { "388", new Jamaica() },
        { "392", new Japan() },
        { "832", new Jersey() },
        { "400", new Jordan() },
        { "398", new Kazakhstan() },
        { "404", new Kenya() },
        { "296", new Kiribati() },
        { "408", new NorthKorea() },
        { "410", new SouthKorea() },
        { "414", new Kuwait() },
        { "417", new Kyrgyzstan() },
        { "418", new LaoPeoplesDemocraticRepublic() },
        { "428", new Latvia() },
        { "422", new Lebanon() },
        { "426", new Lesotho() },
        { "430", new Liberia() },
        { "434", new Libya() },
        { "438", new Liechtenstein() },
        { "440", new Lithuania() },
        { "442", new Luxembourg() },
        { "446", new Macao() },
        { "450", new Madagascar() },
        { "454", new Malawi() },
        { "458", new Malaysia() },
        { "462", new Maldives() },
        { "466", new Mali() },
        { "470", new Malta() },
        { "584", new MarshallIslands() },
        { "474", new Martinique() },
        { "478", new Mauritania() },
        { "480", new Mauritius() },
        { "175", new Mayotte() },
        { "484", new Mexico() },
        { "583", new Micronesia() },
        { "498", new Moldova() },
        { "492", new Monaco() },
        { "496", new Mongolia() },
        { "499", new Montenegro() },
        { "500", new Montserrat() },
        { "504", new Morocco() },
        { "508", new Mozambique() },
        { "104", new Myanmar() },
        { "516", new Namibia() },
        { "520", new Nauru() },
        { "524", new Nepal() },
        { "528", new Netherlands() },
        { "540", new NewCaledonia() },
        { "554", new NewZealand() },
        { "558", new Nicaragua() },
        { "562", new Niger() },
        { "566", new Nigeria() },
        { "570", new Niue() },
        { "574", new NorfolkIsland() },
        { "807", new NorthMacedonia() },
        { "580", new NorthernMarianaIslands() },
        { "578", new Norway() },
        { "512", new Oman() },
        { "586", new Pakistan() },
        { "585", new Palau() },
        { "275", new StateOfPalestine() },
        { "591", new Panama() },
        { "598", new PapuaNewGuinea() },
        { "600", new Paraguay() },
        { "604", new Peru() },
        { "608", new Philippines() },
        { "612", new Pitcairn() },
        { "616", new Poland() },
        { "620", new Portugal() },
        { "630", new PuertoRico() },
        { "634", new Qatar() },
        { "642", new Romania() },
        { "643", new RussianFederation() },
        { "646", new Rwanda() },
        { "638", new Réunion() },
        { "652", new SaintBarthélemy() },
        { "654", new SaintHelenaAscensionAndTristanDaCunha() },
        { "659", new SaintKittsAndNevis() },
        { "662", new SaintLucia() },
        { "663", new SaintMartin() },
        { "666", new SaintPierreAndMiquelon() },
        { "670", new SaintVincentAndTheGrenadines() },
        { "882", new Samoa() },
        { "674", new SanMarino() },
        { "678", new SaoTomeAndPrincipe() },
        { "682", new SaudiArabia() },
        { "686", new Senegal() },
        { "688", new Serbia() },
        { "690", new Seychelles() },
        { "694", new SierraLeone() },
        { "702", new Singapore() },
        { "534", new SintMaarten() },
        { "703", new Slovakia() },
        { "705", new Slovenia() },
        { "090", new SolomonIslands() },
        { "706", new Somalia() },
        { "710", new SouthAfrica() },
        { "239", new SouthGeorgiaAndTheSouthSandwichIslands() },
        { "728", new SouthSudan() },
        { "724", new Spain() },
        { "144", new SriLanka() },
        { "729", new Sudan() },
        { "740", new Suriname() },
        { "744", new SvalbardAndJanMayen() },
        { "752", new Sweden() },
        { "756", new Switzerland() },
        { "760", new SyrianArabRepublic() },
        { "158", new Taiwan() },
        { "762", new Tajikistan() },
        { "834", new TheUnitedRepublicOfTanzania() },
        { "764", new Thailand() },
        { "626", new TimorLeste() },
        { "768", new Togo() },
        { "772", new Tokelau() },
        { "776", new Tonga() },
        { "780", new TrinidadAndTobago() },
        { "788", new Tunisia() },
        { "795", new Turkmenistan() },
        { "796", new TurksAndCaicosIslands() },
        { "798", new Tuvalu() },
        { "792", new Türkiye() },
        { "800", new Uganda() },
        { "804", new Ukraine() },
        { "784", new UnitedArabEmirates() },
        { "826", new UnitedKingdomOfGreatBritainAndNorthernIreland() },
        { "581", new UnitedStatesMinorOutlyingIslands() },
        { "840", new UnitedStatesOfAmerica() },
        { "858", new Uruguay() },
        { "860", new Uzbekistan() },
        { "548", new Vanuatu() },
        { "862", new Venezuela() },
        { "704", new VietNam() },
        { "092", new BritishVirginIslands() },
        { "850", new UsVirginIslands() },
        { "876", new WallisAndFutuna() },
        { "732", new WesternSahara() },
        { "887", new Yemen() },
        { "894", new Zambia() },
        { "716", new Zimbabwe() }
    };

    public static ICountry GetCountryByAlpha2Code(string alpha2Code) =>
        alpha2Code switch {
            "AF" => new Afghanistan(),
            "AL" => new Albania(),
            "DZ" => new Algeria(),
            "AS" => new AmericanSamoa(),
            "AD" => new Andorra(),
            "AO" => new Angola(),
            "AI" => new Anguilla(),
            "AQ" => new Antarctica(),
            "AG" => new AntiguaAndBarbuda(),
            "AR" => new Argentina(),
            "AM" => new Armenia(),
            "AW" => new Aruba(),
            "AU" => new Australia(),
            "AT" => new Austria(),
            "AZ" => new Azerbaijan(),
            "BS" => new Bahamas(),
            "BH" => new Bahrain(),
            "BD" => new Bangladesh(),
            "BB" => new Barbados(),
            "BY" => new Belarus(),
            "BE" => new Belgium(),
            "BZ" => new Belize(),
            "BJ" => new Benin(),
            "BM" => new Bermuda(),
            "AX" => new ÅlandIslands(),
            "BT" => new Bhutan(),
            "BO" => new Bolivia(),
            "BQ" => new BonaireSintEustatiusAndSaba(),
            "BA" => new BosniaAndHerzegovina(),
            "BW" => new Botswana(),
            "BV" => new BouvetIsland(),
            "BR" => new Brazil(),
            "IO" => new BritishIndianOceanTerritory(),
            "BN" => new BruneiDarussalam(),
            "BG" => new Bulgaria(),
            "BF" => new BurkinaFaso(),
            "BI" => new Burundi(),
            "CV" => new CaboVerde(),
            "KH" => new Cambodia(),
            "CM" => new Cameroon(),
            "CA" => new Canada(),
            "KY" => new CaymanIslands(),
            "CF" => new CentralAfricanRepublic(),
            "TD" => new Chad(),
            "CL" => new Chile(),
            "CN" => new China(),
            "CX" => new ChristmasIsland(),
            "CC" => new CocosIslands(),
            "CO" => new Colombia(),
            "KM" => new Comoros(),
            "CD" => new DemocraticRepublicOfTheCongo(),
            "CG" => new Congo(),
            "CK" => new CookIslands(),
            "CR" => new CostaRica(),
            "HR" => new Croatia(),
            "CU" => new Cuba(),
            "CW" => new Curaçao(),
            "CY" => new Cyprus(),
            "CZ" => new Czechia(),
            "CI" => new CôteDivoire(),
            "DK" => new Denmark(),
            "DJ" => new Djibouti(),
            "DM" => new Dominica(),
            "DO" => new DominicanRepublic(),
            "EC" => new Ecuador(),
            "EG" => new Egypt(),
            "SV" => new ElSalvador(),
            "GQ" => new EquatorialGuinea(),
            "ER" => new Eritrea(),
            "EE" => new Estonia(),
            "SZ" => new Eswatini(),
            "ET" => new Ethiopia(),
            "FK" => new FalklandIslands(),
            "FO" => new FaroeIslands(),
            "FJ" => new Fiji(),
            "FI" => new Finland(),
            "FR" => new France(),
            "GF" => new FrenchGuiana(),
            "PF" => new FrenchPolynesia(),
            "TF" => new FrenchSouthernTerritories(),
            "GA" => new Gabon(),
            "GM" => new Gambia(),
            "GE" => new Georgia(),
            "DE" => new Germany(),
            "GH" => new Ghana(),
            "GI" => new Gibraltar(),
            "GR" => new Greece(),
            "GL" => new Greenland(),
            "GD" => new Grenada(),
            "GP" => new Guadeloupe(),
            "GU" => new Guam(),
            "GT" => new Guatemala(),
            "GG" => new Guernsey(),
            "GN" => new Guinea(),
            "GW" => new GuineaBissau(),
            "GY" => new Guyana(),
            "HT" => new Haiti(),
            "HM" => new HeardIslandAndMcDonaldIslands(),
            "VA" => new HolySee(),
            "HN" => new Honduras(),
            "HK" => new HongKong(),
            "HU" => new Hungary(),
            "IS" => new Iceland(),
            "IN" => new India(),
            "ID" => new Indonesia(),
            "IR" => new Iran(),
            "IQ" => new Iraq(),
            "IE" => new Ireland(),
            "IM" => new IsleOfMan(),
            "IL" => new Israel(),
            "IT" => new Italy(),
            "JM" => new Jamaica(),
            "JP" => new Japan(),
            "JE" => new Jersey(),
            "JO" => new Jordan(),
            "KZ" => new Kazakhstan(),
            "KE" => new Kenya(),
            "KI" => new Kiribati(),
            "KP" => new NorthKorea(),
            "KR" => new SouthKorea(),
            "KW" => new Kuwait(),
            "KG" => new Kyrgyzstan(),
            "LA" => new LaoPeoplesDemocraticRepublic(),
            "LV" => new Latvia(),
            "LB" => new Lebanon(),
            "LS" => new Lesotho(),
            "LR" => new Liberia(),
            "LY" => new Libya(),
            "LI" => new Liechtenstein(),
            "LT" => new Lithuania(),
            "LU" => new Luxembourg(),
            "MO" => new Macao(),
            "MG" => new Madagascar(),
            "MW" => new Malawi(),
            "MY" => new Malaysia(),
            "MV" => new Maldives(),
            "ML" => new Mali(),
            "MT" => new Malta(),
            "MH" => new MarshallIslands(),
            "MQ" => new Martinique(),
            "MR" => new Mauritania(),
            "MU" => new Mauritius(),
            "YT" => new Mayotte(),
            "MX" => new Mexico(),
            "FM" => new Micronesia(),
            "MD" => new Moldova(),
            "MC" => new Monaco(),
            "MN" => new Mongolia(),
            "ME" => new Montenegro(),
            "MS" => new Montserrat(),
            "MA" => new Morocco(),
            "MZ" => new Mozambique(),
            "MM" => new Myanmar(),
            "NA" => new Namibia(),
            "NR" => new Nauru(),
            "NP" => new Nepal(),
            "NL" => new Netherlands(),
            "NC" => new NewCaledonia(),
            "NZ" => new NewZealand(),
            "NI" => new Nicaragua(),
            "NE" => new Niger(),
            "NG" => new Nigeria(),
            "NU" => new Niue(),
            "NF" => new NorfolkIsland(),
            "MK" => new NorthMacedonia(),
            "MP" => new NorthernMarianaIslands(),
            "NO" => new Norway(),
            "OM" => new Oman(),
            "PK" => new Pakistan(),
            "PW" => new Palau(),
            "PS" => new StateOfPalestine(),
            "PA" => new Panama(),
            "PG" => new PapuaNewGuinea(),
            "PY" => new Paraguay(),
            "PE" => new Peru(),
            "PH" => new Philippines(),
            "PN" => new Pitcairn(),
            "PL" => new Poland(),
            "PT" => new Portugal(),
            "PR" => new PuertoRico(),
            "QA" => new Qatar(),
            "RO" => new Romania(),
            "RU" => new RussianFederation(),
            "RW" => new Rwanda(),
            "RE" => new Réunion(),
            "BL" => new SaintBarthélemy(),
            "SH" => new SaintHelenaAscensionAndTristanDaCunha(),
            "KN" => new SaintKittsAndNevis(),
            "LC" => new SaintLucia(),
            "MF" => new SaintMartin(),
            "PM" => new SaintPierreAndMiquelon(),
            "VC" => new SaintVincentAndTheGrenadines(),
            "WS" => new Samoa(),
            "SM" => new SanMarino(),
            "ST" => new SaoTomeAndPrincipe(),
            "SA" => new SaudiArabia(),
            "SN" => new Senegal(),
            "RS" => new Serbia(),
            "SC" => new Seychelles(),
            "SL" => new SierraLeone(),
            "SG" => new Singapore(),
            "SX" => new SintMaarten(),
            "SK" => new Slovakia(),
            "SI" => new Slovenia(),
            "SB" => new SolomonIslands(),
            "SO" => new Somalia(),
            "ZA" => new SouthAfrica(),
            "GS" => new SouthGeorgiaAndTheSouthSandwichIslands(),
            "SS" => new SouthSudan(),
            "ES" => new Spain(),
            "LK" => new SriLanka(),
            "SD" => new Sudan(),
            "SR" => new Suriname(),
            "SJ" => new SvalbardAndJanMayen(),
            "SE" => new Sweden(),
            "CH" => new Switzerland(),
            "SY" => new SyrianArabRepublic(),
            "TW" => new Taiwan(),
            "TJ" => new Tajikistan(),
            "TZ" => new TheUnitedRepublicOfTanzania(),
            "TH" => new Thailand(),
            "TL" => new TimorLeste(),
            "TG" => new Togo(),
            "TK" => new Tokelau(),
            "TO" => new Tonga(),
            "TT" => new TrinidadAndTobago(),
            "TN" => new Tunisia(),
            "TM" => new Turkmenistan(),
            "TC" => new TurksAndCaicosIslands(),
            "TV" => new Tuvalu(),
            "TR" => new Türkiye(),
            "UG" => new Uganda(),
            "UA" => new Ukraine(),
            "AE" => new UnitedArabEmirates(),
            "GB" => new UnitedKingdomOfGreatBritainAndNorthernIreland(),
            "UM" => new UnitedStatesMinorOutlyingIslands(),
            "US" => new UnitedStatesOfAmerica(),
            "UY" => new Uruguay(),
            "UZ" => new Uzbekistan(),
            "VU" => new Vanuatu(),
            "VE" => new Venezuela(),
            "VN" => new VietNam(),
            "VG" => new BritishVirginIslands(),
            "VI" => new UsVirginIslands(),
            "WF" => new WallisAndFutuna(),
            "EH" => new WesternSahara(),
            "YE" => new Yemen(),
            "ZM" => new Zambia(),
            "ZW" => new Zimbabwe(),
            _ => throw new ArgumentOutOfRangeException(nameof(alpha2Code), alpha2Code, null)
        };

    public static ICountry GetCountryByAlpha3Code(string alpha3Code) =>
        alpha3Code switch {
            "AFG" => new Afghanistan(),
            "ALB" => new Albania(),
            "DZA" => new Algeria(),
            "ASM" => new AmericanSamoa(),
            "AND" => new Andorra(),
            "AGO" => new Angola(),
            "AIA" => new Anguilla(),
            "ATA" => new Antarctica(),
            "ATG" => new AntiguaAndBarbuda(),
            "ARG" => new Argentina(),
            "ARM" => new Armenia(),
            "ABW" => new Aruba(),
            "AUS" => new Australia(),
            "AUT" => new Austria(),
            "AZE" => new Azerbaijan(),
            "BHS" => new Bahamas(),
            "BHR" => new Bahrain(),
            "BGD" => new Bangladesh(),
            "BRB" => new Barbados(),
            "BLR" => new Belarus(),
            "BEL" => new Belgium(),
            "BLZ" => new Belize(),
            "BEN" => new Benin(),
            "BMU" => new Bermuda(),
            "ALA" => new ÅlandIslands(),
            "BTN" => new Bhutan(),
            "BOL" => new Bolivia(),
            "BES" => new BonaireSintEustatiusAndSaba(),
            "BIH" => new BosniaAndHerzegovina(),
            "BWA" => new Botswana(),
            "BVT" => new BouvetIsland(),
            "BRA" => new Brazil(),
            "IOT" => new BritishIndianOceanTerritory(),
            "BRN" => new BruneiDarussalam(),
            "BGR" => new Bulgaria(),
            "BFA" => new BurkinaFaso(),
            "BDI" => new Burundi(),
            "CPV" => new CaboVerde(),
            "KHM" => new Cambodia(),
            "CMR" => new Cameroon(),
            "CAN" => new Canada(),
            "CYM" => new CaymanIslands(),
            "CAF" => new CentralAfricanRepublic(),
            "TCD" => new Chad(),
            "CHL" => new Chile(),
            "CHN" => new China(),
            "CXR" => new ChristmasIsland(),
            "CCK" => new CocosIslands(),
            "COL" => new Colombia(),
            "COM" => new Comoros(),
            "COD" => new DemocraticRepublicOfTheCongo(),
            "COG" => new Congo(),
            "COK" => new CookIslands(),
            "CRI" => new CostaRica(),
            "HRV" => new Croatia(),
            "CUB" => new Cuba(),
            "CUW" => new Curaçao(),
            "CYP" => new Cyprus(),
            "CZE" => new Czechia(),
            "CIV" => new CôteDivoire(),
            "DNK" => new Denmark(),
            "DJI" => new Djibouti(),
            "DMA" => new Dominica(),
            "DOM" => new DominicanRepublic(),
            "ECU" => new Ecuador(),
            "EGY" => new Egypt(),
            "SLV" => new ElSalvador(),
            "GNQ" => new EquatorialGuinea(),
            "ERI" => new Eritrea(),
            "EST" => new Estonia(),
            "SWZ" => new Eswatini(),
            "ETH" => new Ethiopia(),
            "FLK" => new FalklandIslands(),
            "FRO" => new FaroeIslands(),
            "FJI" => new Fiji(),
            "FIN" => new Finland(),
            "FRA" => new France(),
            "GUF" => new FrenchGuiana(),
            "PYF" => new FrenchPolynesia(),
            "ATF" => new FrenchSouthernTerritories(),
            "GAB" => new Gabon(),
            "GMB" => new Gambia(),
            "GEO" => new Georgia(),
            "DEU" => new Germany(),
            "GHA" => new Ghana(),
            "GIB" => new Gibraltar(),
            "GRC" => new Greece(),
            "GRL" => new Greenland(),
            "GRD" => new Grenada(),
            "GLP" => new Guadeloupe(),
            "GUM" => new Guam(),
            "GTM" => new Guatemala(),
            "GGY" => new Guernsey(),
            "GIN" => new Guinea(),
            "GNB" => new GuineaBissau(),
            "GUY" => new Guyana(),
            "HTI" => new Haiti(),
            "HMD" => new HeardIslandAndMcDonaldIslands(),
            "VAT" => new HolySee(),
            "HND" => new Honduras(),
            "HKG" => new HongKong(),
            "HUN" => new Hungary(),
            "ISL" => new Iceland(),
            "IND" => new India(),
            "IDN" => new Indonesia(),
            "IRN" => new Iran(),
            "IRQ" => new Iraq(),
            "IRL" => new Ireland(),
            "IMN" => new IsleOfMan(),
            "ISR" => new Israel(),
            "ITA" => new Italy(),
            "JAM" => new Jamaica(),
            "JPN" => new Japan(),
            "JEY" => new Jersey(),
            "JOR" => new Jordan(),
            "KAZ" => new Kazakhstan(),
            "KEN" => new Kenya(),
            "KIR" => new Kiribati(),
            "PRK" => new NorthKorea(),
            "KOR" => new SouthKorea(),
            "KWT" => new Kuwait(),
            "KGZ" => new Kyrgyzstan(),
            "LAO" => new LaoPeoplesDemocraticRepublic(),
            "LVA" => new Latvia(),
            "LBN" => new Lebanon(),
            "LSO" => new Lesotho(),
            "LBR" => new Liberia(),
            "LBY" => new Libya(),
            "LIE" => new Liechtenstein(),
            "LTU" => new Lithuania(),
            "LUX" => new Luxembourg(),
            "MAC" => new Macao(),
            "MDG" => new Madagascar(),
            "MWI" => new Malawi(),
            "MYS" => new Malaysia(),
            "MDV" => new Maldives(),
            "MLI" => new Mali(),
            "MLT" => new Malta(),
            "MHL" => new MarshallIslands(),
            "MTQ" => new Martinique(),
            "MRT" => new Mauritania(),
            "MUS" => new Mauritius(),
            "MYT" => new Mayotte(),
            "MEX" => new Mexico(),
            "FSM" => new Micronesia(),
            "MDA" => new Moldova(),
            "MCO" => new Monaco(),
            "MNG" => new Mongolia(),
            "MNE" => new Montenegro(),
            "MSR" => new Montserrat(),
            "MAR" => new Morocco(),
            "MOZ" => new Mozambique(),
            "MMR" => new Myanmar(),
            "NAM" => new Namibia(),
            "NRU" => new Nauru(),
            "NPL" => new Nepal(),
            "NLD" => new Netherlands(),
            "NCL" => new NewCaledonia(),
            "NZL" => new NewZealand(),
            "NIC" => new Nicaragua(),
            "NER" => new Niger(),
            "NGA" => new Nigeria(),
            "NIU" => new Niue(),
            "NFK" => new NorfolkIsland(),
            "MKD" => new NorthMacedonia(),
            "MNP" => new NorthernMarianaIslands(),
            "NOR" => new Norway(),
            "OMN" => new Oman(),
            "PAK" => new Pakistan(),
            "PLW" => new Palau(),
            "PSE" => new StateOfPalestine(),
            "PAN" => new Panama(),
            "PNG" => new PapuaNewGuinea(),
            "PRY" => new Paraguay(),
            "PER" => new Peru(),
            "PHL" => new Philippines(),
            "PCN" => new Pitcairn(),
            "POL" => new Poland(),
            "PRT" => new Portugal(),
            "PRI" => new PuertoRico(),
            "QAT" => new Qatar(),
            "ROU" => new Romania(),
            "RUS" => new RussianFederation(),
            "RWA" => new Rwanda(),
            "REU" => new Réunion(),
            "BLM" => new SaintBarthélemy(),
            "SHN" => new SaintHelenaAscensionAndTristanDaCunha(),
            "KNA" => new SaintKittsAndNevis(),
            "LCA" => new SaintLucia(),
            "MAF" => new SaintMartin(),
            "SPM" => new SaintPierreAndMiquelon(),
            "VCT" => new SaintVincentAndTheGrenadines(),
            "WSM" => new Samoa(),
            "SMR" => new SanMarino(),
            "STP" => new SaoTomeAndPrincipe(),
            "SAU" => new SaudiArabia(),
            "SEN" => new Senegal(),
            "SRB" => new Serbia(),
            "SYC" => new Seychelles(),
            "SLE" => new SierraLeone(),
            "SGP" => new Singapore(),
            "SXM" => new SintMaarten(),
            "SVK" => new Slovakia(),
            "SVN" => new Slovenia(),
            "SLB" => new SolomonIslands(),
            "SOM" => new Somalia(),
            "ZAF" => new SouthAfrica(),
            "SGS" => new SouthGeorgiaAndTheSouthSandwichIslands(),
            "SSD" => new SouthSudan(),
            "ESP" => new Spain(),
            "LKA" => new SriLanka(),
            "SDN" => new Sudan(),
            "SUR" => new Suriname(),
            "SJM" => new SvalbardAndJanMayen(),
            "SWE" => new Sweden(),
            "CHE" => new Switzerland(),
            "SYR" => new SyrianArabRepublic(),
            "TWN" => new Taiwan(),
            "TJK" => new Tajikistan(),
            "TZA" => new TheUnitedRepublicOfTanzania(),
            "THA" => new Thailand(),
            "TLS" => new TimorLeste(),
            "TGO" => new Togo(),
            "TKL" => new Tokelau(),
            "TON" => new Tonga(),
            "TTO" => new TrinidadAndTobago(),
            "TUN" => new Tunisia(),
            "TKM" => new Turkmenistan(),
            "TCA" => new TurksAndCaicosIslands(),
            "TUV" => new Tuvalu(),
            "TUR" => new Türkiye(),
            "UGA" => new Uganda(),
            "UKR" => new Ukraine(),
            "ARE" => new UnitedArabEmirates(),
            "GBR" => new UnitedKingdomOfGreatBritainAndNorthernIreland(),
            "UMI" => new UnitedStatesMinorOutlyingIslands(),
            "USA" => new UnitedStatesOfAmerica(),
            "URY" => new Uruguay(),
            "UZB" => new Uzbekistan(),
            "VUT" => new Vanuatu(),
            "VEN" => new Venezuela(),
            "VNM" => new VietNam(),
            "VGB" => new BritishVirginIslands(),
            "VIR" => new UsVirginIslands(),
            "WLF" => new WallisAndFutuna(),
            "ESH" => new WesternSahara(),
            "YEM" => new Yemen(),
            "ZMB" => new Zambia(),
            "ZWE" => new Zimbabwe(),
            _ => throw new ArgumentOutOfRangeException(nameof(alpha3Code), alpha3Code, null)
        };

    public static ICountry GetCountryByNumericCode(int numericCode) =>
        GetCountryByNumericCode(numericCode.ToString("000"));

    public static ICountry GetCountryByNumericCode(string numericCode) =>
        numericCode switch {
            "004" => new Afghanistan(),
            "008" => new Albania(),
            "012" => new Algeria(),
            "016" => new AmericanSamoa(),
            "020" => new Andorra(),
            "024" => new Angola(),
            "660" => new Anguilla(),
            "010" => new Antarctica(),
            "028" => new AntiguaAndBarbuda(),
            "032" => new Argentina(),
            "051" => new Armenia(),
            "533" => new Aruba(),
            "036" => new Australia(),
            "040" => new Austria(),
            "031" => new Azerbaijan(),
            "044" => new Bahamas(),
            "048" => new Bahrain(),
            "050" => new Bangladesh(),
            "052" => new Barbados(),
            "112" => new Belarus(),
            "056" => new Belgium(),
            "084" => new Belize(),
            "204" => new Benin(),
            "060" => new Bermuda(),
            "248" => new ÅlandIslands(),
            "064" => new Bhutan(),
            "068" => new Bolivia(),
            "535" => new BonaireSintEustatiusAndSaba(),
            "070" => new BosniaAndHerzegovina(),
            "072" => new Botswana(),
            "074" => new BouvetIsland(),
            "076" => new Brazil(),
            "086" => new BritishIndianOceanTerritory(),
            "096" => new BruneiDarussalam(),
            "100" => new Bulgaria(),
            "854" => new BurkinaFaso(),
            "108" => new Burundi(),
            "132" => new CaboVerde(),
            "116" => new Cambodia(),
            "120" => new Cameroon(),
            "124" => new Canada(),
            "136" => new CaymanIslands(),
            "140" => new CentralAfricanRepublic(),
            "148" => new Chad(),
            "152" => new Chile(),
            "156" => new China(),
            "162" => new ChristmasIsland(),
            "166" => new CocosIslands(),
            "170" => new Colombia(),
            "174" => new Comoros(),
            "180" => new DemocraticRepublicOfTheCongo(),
            "178" => new Congo(),
            "184" => new CookIslands(),
            "188" => new CostaRica(),
            "191" => new Croatia(),
            "192" => new Cuba(),
            "531" => new Curaçao(),
            "196" => new Cyprus(),
            "203" => new Czechia(),
            "384" => new CôteDivoire(),
            "208" => new Denmark(),
            "262" => new Djibouti(),
            "212" => new Dominica(),
            "214" => new DominicanRepublic(),
            "218" => new Ecuador(),
            "818" => new Egypt(),
            "222" => new ElSalvador(),
            "226" => new EquatorialGuinea(),
            "232" => new Eritrea(),
            "233" => new Estonia(),
            "748" => new Eswatini(),
            "231" => new Ethiopia(),
            "238" => new FalklandIslands(),
            "234" => new FaroeIslands(),
            "242" => new Fiji(),
            "246" => new Finland(),
            "250" => new France(),
            "254" => new FrenchGuiana(),
            "258" => new FrenchPolynesia(),
            "260" => new FrenchSouthernTerritories(),
            "266" => new Gabon(),
            "270" => new Gambia(),
            "268" => new Georgia(),
            "276" => new Germany(),
            "288" => new Ghana(),
            "292" => new Gibraltar(),
            "300" => new Greece(),
            "304" => new Greenland(),
            "308" => new Grenada(),
            "312" => new Guadeloupe(),
            "316" => new Guam(),
            "320" => new Guatemala(),
            "831" => new Guernsey(),
            "324" => new Guinea(),
            "624" => new GuineaBissau(),
            "328" => new Guyana(),
            "332" => new Haiti(),
            "334" => new HeardIslandAndMcDonaldIslands(),
            "336" => new HolySee(),
            "340" => new Honduras(),
            "344" => new HongKong(),
            "348" => new Hungary(),
            "352" => new Iceland(),
            "356" => new India(),
            "360" => new Indonesia(),
            "364" => new Iran(),
            "368" => new Iraq(),
            "372" => new Ireland(),
            "833" => new IsleOfMan(),
            "376" => new Israel(),
            "380" => new Italy(),
            "388" => new Jamaica(),
            "392" => new Japan(),
            "832" => new Jersey(),
            "400" => new Jordan(),
            "398" => new Kazakhstan(),
            "404" => new Kenya(),
            "296" => new Kiribati(),
            "408" => new NorthKorea(),
            "410" => new SouthKorea(),
            "414" => new Kuwait(),
            "417" => new Kyrgyzstan(),
            "418" => new LaoPeoplesDemocraticRepublic(),
            "428" => new Latvia(),
            "422" => new Lebanon(),
            "426" => new Lesotho(),
            "430" => new Liberia(),
            "434" => new Libya(),
            "438" => new Liechtenstein(),
            "440" => new Lithuania(),
            "442" => new Luxembourg(),
            "446" => new Macao(),
            "450" => new Madagascar(),
            "454" => new Malawi(),
            "458" => new Malaysia(),
            "462" => new Maldives(),
            "466" => new Mali(),
            "470" => new Malta(),
            "584" => new MarshallIslands(),
            "474" => new Martinique(),
            "478" => new Mauritania(),
            "480" => new Mauritius(),
            "175" => new Mayotte(),
            "484" => new Mexico(),
            "583" => new Micronesia(),
            "498" => new Moldova(),
            "492" => new Monaco(),
            "496" => new Mongolia(),
            "499" => new Montenegro(),
            "500" => new Montserrat(),
            "504" => new Morocco(),
            "508" => new Mozambique(),
            "104" => new Myanmar(),
            "516" => new Namibia(),
            "520" => new Nauru(),
            "524" => new Nepal(),
            "528" => new Netherlands(),
            "540" => new NewCaledonia(),
            "554" => new NewZealand(),
            "558" => new Nicaragua(),
            "562" => new Niger(),
            "566" => new Nigeria(),
            "570" => new Niue(),
            "574" => new NorfolkIsland(),
            "807" => new NorthMacedonia(),
            "580" => new NorthernMarianaIslands(),
            "578" => new Norway(),
            "512" => new Oman(),
            "586" => new Pakistan(),
            "585" => new Palau(),
            "275" => new StateOfPalestine(),
            "591" => new Panama(),
            "598" => new PapuaNewGuinea(),
            "600" => new Paraguay(),
            "604" => new Peru(),
            "608" => new Philippines(),
            "612" => new Pitcairn(),
            "616" => new Poland(),
            "620" => new Portugal(),
            "630" => new PuertoRico(),
            "634" => new Qatar(),
            "642" => new Romania(),
            "643" => new RussianFederation(),
            "646" => new Rwanda(),
            "638" => new Réunion(),
            "652" => new SaintBarthélemy(),
            "654" => new SaintHelenaAscensionAndTristanDaCunha(),
            "659" => new SaintKittsAndNevis(),
            "662" => new SaintLucia(),
            "663" => new SaintMartin(),
            "666" => new SaintPierreAndMiquelon(),
            "670" => new SaintVincentAndTheGrenadines(),
            "882" => new Samoa(),
            "674" => new SanMarino(),
            "678" => new SaoTomeAndPrincipe(),
            "682" => new SaudiArabia(),
            "686" => new Senegal(),
            "688" => new Serbia(),
            "690" => new Seychelles(),
            "694" => new SierraLeone(),
            "702" => new Singapore(),
            "534" => new SintMaarten(),
            "703" => new Slovakia(),
            "705" => new Slovenia(),
            "090" => new SolomonIslands(),
            "706" => new Somalia(),
            "710" => new SouthAfrica(),
            "239" => new SouthGeorgiaAndTheSouthSandwichIslands(),
            "728" => new SouthSudan(),
            "724" => new Spain(),
            "144" => new SriLanka(),
            "729" => new Sudan(),
            "740" => new Suriname(),
            "744" => new SvalbardAndJanMayen(),
            "752" => new Sweden(),
            "756" => new Switzerland(),
            "760" => new SyrianArabRepublic(),
            "158" => new Taiwan(),
            "762" => new Tajikistan(),
            "834" => new TheUnitedRepublicOfTanzania(),
            "764" => new Thailand(),
            "626" => new TimorLeste(),
            "768" => new Togo(),
            "772" => new Tokelau(),
            "776" => new Tonga(),
            "780" => new TrinidadAndTobago(),
            "788" => new Tunisia(),
            "795" => new Turkmenistan(),
            "796" => new TurksAndCaicosIslands(),
            "798" => new Tuvalu(),
            "792" => new Türkiye(),
            "800" => new Uganda(),
            "804" => new Ukraine(),
            "784" => new UnitedArabEmirates(),
            "826" => new UnitedKingdomOfGreatBritainAndNorthernIreland(),
            "581" => new UnitedStatesMinorOutlyingIslands(),
            "840" => new UnitedStatesOfAmerica(),
            "858" => new Uruguay(),
            "860" => new Uzbekistan(),
            "548" => new Vanuatu(),
            "862" => new Venezuela(),
            "704" => new VietNam(),
            "092" => new BritishVirginIslands(),
            "850" => new UsVirginIslands(),
            "876" => new WallisAndFutuna(),
            "732" => new WesternSahara(),
            "887" => new Yemen(),
            "894" => new Zambia(),
            "716" => new Zimbabwe(),
            _ => throw new ArgumentOutOfRangeException(nameof(numericCode), numericCode, null)
        };
}